<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Masjid" Member="Masjids">
    <Type Name="Masjid">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="Area" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="Fajar" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Zohar" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Asar" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Magrib" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Esha" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>