#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prayer_Timings_Schedule_For_Masjid.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMasjid(Masjid instance);
    partial void UpdateMasjid(Masjid instance);
    partial void DeleteMasjid(Masjid instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DatabaseConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Masjid> Masjids
		{
			get
			{
				return this.GetTable<Masjid>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Masjid")]
	public partial class Masjid : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Address;
		
		private string _Name;
		
		private string _Area;
		
		private string _Fajar;
		
		private string _Zohar;
		
		private string _Asar;
		
		private string _Magrib;
		
		private string _Esha;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAreaChanging(string value);
    partial void OnAreaChanged();
    partial void OnFajarChanging(string value);
    partial void OnFajarChanged();
    partial void OnZoharChanging(string value);
    partial void OnZoharChanged();
    partial void OnAsarChanging(string value);
    partial void OnAsarChanged();
    partial void OnMagribChanging(string value);
    partial void OnMagribChanged();
    partial void OnEshaChanging(string value);
    partial void OnEshaChanged();
    #endregion
		
		public Masjid()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NChar(100)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="NChar(100)")]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this.OnAreaChanging(value);
					this.SendPropertyChanging();
					this._Area = value;
					this.SendPropertyChanged("Area");
					this.OnAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fajar", DbType="NChar(10)")]
		public string Fajar
		{
			get
			{
				return this._Fajar;
			}
			set
			{
				if ((this._Fajar != value))
				{
					this.OnFajarChanging(value);
					this.SendPropertyChanging();
					this._Fajar = value;
					this.SendPropertyChanged("Fajar");
					this.OnFajarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zohar", DbType="NChar(10)")]
		public string Zohar
		{
			get
			{
				return this._Zohar;
			}
			set
			{
				if ((this._Zohar != value))
				{
					this.OnZoharChanging(value);
					this.SendPropertyChanging();
					this._Zohar = value;
					this.SendPropertyChanged("Zohar");
					this.OnZoharChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asar", DbType="NChar(10)")]
		public string Asar
		{
			get
			{
				return this._Asar;
			}
			set
			{
				if ((this._Asar != value))
				{
					this.OnAsarChanging(value);
					this.SendPropertyChanging();
					this._Asar = value;
					this.SendPropertyChanged("Asar");
					this.OnAsarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Magrib", DbType="NChar(10)")]
		public string Magrib
		{
			get
			{
				return this._Magrib;
			}
			set
			{
				if ((this._Magrib != value))
				{
					this.OnMagribChanging(value);
					this.SendPropertyChanging();
					this._Magrib = value;
					this.SendPropertyChanged("Magrib");
					this.OnMagribChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Esha", DbType="NChar(10)")]
		public string Esha
		{
			get
			{
				return this._Esha;
			}
			set
			{
				if ((this._Esha != value))
				{
					this.OnEshaChanging(value);
					this.SendPropertyChanging();
					this._Esha = value;
					this.SendPropertyChanged("Esha");
					this.OnEshaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
